//
// SixLinkedProfilesProficiency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum SixLinkedProfilesProficiency: String, Codable, CaseIterable {
    case elementary = "Elementary"
    case limited = "Limited"
    case professional = "Professional"
    case full = "Full"
    case nativeBillingual = "NativeBillingual"
}
