//
// SixLinkedNotificationsNotificationSeverity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum SixLinkedNotificationsNotificationSeverity: String, Codable, CaseIterable {
    case info = "Info"
    case success = "Success"
    case warning = "Warning"
    case danger = "Danger"
    case fatal = "Fatal"
}
