//
// SixLinkedAddressesDtosSimpleAddressDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedAddressesDtosSimpleAddressDto: Codable, Hashable {

    public var city: SixLinkedCitiesDtosCityDto?
    public var province: SixLinkedProvincesDtosProvinceDto?
    public var country: SixLinkedCountriesDtosCountryDto?

    public init(city: SixLinkedCitiesDtosCityDto? = nil, province: SixLinkedProvincesDtosProvinceDto? = nil, country: SixLinkedCountriesDtosCountryDto? = nil) {
        self.city = city
        self.province = province
        self.country = country
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case city
        case province
        case country
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(city, forKey: .city)
        try container.encodeIfPresent(province, forKey: .province)
        try container.encodeIfPresent(country, forKey: .country)
    }



}
