//
// SixLinkedPublicationsVisibilityType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum SixLinkedPublicationsVisibilityType: String, Codable, CaseIterable {
    case _public = "Public"
    case registeredUsers = "RegisteredUsers"
    case contacts = "Contacts"
    case selectedContacts = "SelectedContacts"
    case _private = "Private"
}
