//
// SixLinkedNotificationsDtosCreateUpdateUserNotificationDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedNotificationsDtosCreateUpdateUserNotificationDto: Codable, Hashable {

    public var userId: UUID?
    public var notificationId: UUID?
    public var notification: SixLinkedNotificationsDtosCreateUpdateNotificationDto?
    public var state: SixLinkedNotificationsNotificationState?

    public init(userId: UUID? = nil, notificationId: UUID? = nil, notification: SixLinkedNotificationsDtosCreateUpdateNotificationDto? = nil, state: SixLinkedNotificationsNotificationState? = nil) {
        self.userId = userId
        self.notificationId = notificationId
        self.notification = notification
        self.state = state
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case notificationId
        case notification
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(notificationId, forKey: .notificationId)
        try container.encodeIfPresent(notification, forKey: .notification)
        try container.encodeIfPresent(state, forKey: .state)
    }



}
