//
// SixLinkedProfilesDtosProfileLanguageDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedProfilesDtosProfileLanguageDto: Codable, Hashable {

    public var language: SixLinkedLanguagesDtosLanguageDto?
    public var languageId: UUID?
    public var proficiency: SixLinkedProfilesProficiency?

    public init(language: SixLinkedLanguagesDtosLanguageDto? = nil, languageId: UUID? = nil, proficiency: SixLinkedProfilesProficiency? = nil) {
        self.language = language
        self.languageId = languageId
        self.proficiency = proficiency
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case language
        case languageId
        case proficiency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(languageId, forKey: .languageId)
        try container.encodeIfPresent(proficiency, forKey: .proficiency)
    }



}
