//
// SixLinkedLanguagesDtosCreateUpdateLanguageDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedLanguagesDtosCreateUpdateLanguageDto: Codable, Hashable {

    public var profileId: UUID?
    public var profile: SixLinkedProfilesDtosProfileDto?
    public var name: String?
    public var slug: String?

    public init(profileId: UUID? = nil, profile: SixLinkedProfilesDtosProfileDto? = nil, name: String? = nil, slug: String? = nil) {
        self.profileId = profileId
        self.profile = profile
        self.name = name
        self.slug = slug
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profileId
        case profile
        case name
        case slug
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(profileId, forKey: .profileId)
        try container.encodeIfPresent(profile, forKey: .profile)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(slug, forKey: .slug)
    }



}
