//
// SixLinkedAddressDetailsDtosAddressDetailDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedAddressDetailsDtosAddressDetailDto: Codable, Hashable {

    public var streetNumber: String?
    public var route: String?
    public var locality: String?
    public var administrativeAreaLevel2: String?
    public var administrativeAreaLevel1: String?
    public var country: String?
    public var postalCode: String?

    public init(streetNumber: String? = nil, route: String? = nil, locality: String? = nil, administrativeAreaLevel2: String? = nil, administrativeAreaLevel1: String? = nil, country: String? = nil, postalCode: String? = nil) {
        self.streetNumber = streetNumber
        self.route = route
        self.locality = locality
        self.administrativeAreaLevel2 = administrativeAreaLevel2
        self.administrativeAreaLevel1 = administrativeAreaLevel1
        self.country = country
        self.postalCode = postalCode
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case streetNumber
        case route
        case locality
        case administrativeAreaLevel2
        case administrativeAreaLevel1
        case country
        case postalCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(streetNumber, forKey: .streetNumber)
        try container.encodeIfPresent(route, forKey: .route)
        try container.encodeIfPresent(locality, forKey: .locality)
        try container.encodeIfPresent(administrativeAreaLevel2, forKey: .administrativeAreaLevel2)
        try container.encodeIfPresent(administrativeAreaLevel1, forKey: .administrativeAreaLevel1)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(postalCode, forKey: .postalCode)
    }



}
