//
// SixLinkedWorkExperiencesDtosCreateUpdateWorkExperienceDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedWorkExperiencesDtosCreateUpdateWorkExperienceDto: Codable, Hashable {

    public var profileId: UUID?
    public var profile: SixLinkedProfilesDtosProfileDto?
    public var startDate: Date?
    public var endDate: Date?
    public var jobTitle: String?
    public var description: String?
    public var companyName: String?

    public init(profileId: UUID? = nil, profile: SixLinkedProfilesDtosProfileDto? = nil, startDate: Date? = nil, endDate: Date? = nil, jobTitle: String? = nil, description: String? = nil, companyName: String? = nil) {
        self.profileId = profileId
        self.profile = profile
        self.startDate = startDate
        self.endDate = endDate
        self.jobTitle = jobTitle
        self.description = description
        self.companyName = companyName
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profileId
        case profile
        case startDate
        case endDate
        case jobTitle
        case description
        case companyName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(profileId, forKey: .profileId)
        try container.encodeIfPresent(profile, forKey: .profile)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(jobTitle, forKey: .jobTitle)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(companyName, forKey: .companyName)
    }



}
