//
// SixLinkedProjectsParticipantType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum SixLinkedProjectsParticipantType: String, Codable, CaseIterable {
    case undefined = "Undefined"
    case companyUser = "CompanyUser"
    case contractor = "Contractor"
}
