//
// SixLinkedProposalsDtosCreateRequirementFulfillmentDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedProposalsDtosCreateRequirementFulfillmentDto: Codable, Hashable {

    public var requirementId: UUID?
    public var response: String?
    public var file: Data?
    public var type: SixLinkedRequirementsRequirementType?

    public init(requirementId: UUID? = nil, response: String? = nil, file: Data? = nil, type: SixLinkedRequirementsRequirementType? = nil) {
        self.requirementId = requirementId
        self.response = response
        self.file = file
        self.type = type
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requirementId
        case response
        case file
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(requirementId, forKey: .requirementId)
        try container.encodeIfPresent(response, forKey: .response)
        try container.encodeIfPresent(file, forKey: .file)
        try container.encodeIfPresent(type, forKey: .type)
    }



}
