//
// SixLinkedPublicationsStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum SixLinkedPublicationsStatus: String, Codable, CaseIterable {
    case undefined = "Undefined"
    case draft = "Draft"
    case published = "Published"
    case cancelled = "Cancelled"
    case accepted = "Accepted"
    case ended = "Ended"
}
