//
// SixLinkedOrganizationUnitsDtosCreateOrganizationUnitInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedOrganizationUnitsDtosCreateOrganizationUnitInput: Codable, Hashable {

    public var parentId: UUID?
    public var displayName: String

    public init(parentId: UUID? = nil, displayName: String) {
        self.parentId = parentId
        self.displayName = displayName
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parentId
        case displayName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(displayName, forKey: .displayName)
    }



}
