//
// SixLinkedTasksDtosCreateTaskDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedTasksDtosCreateTaskDto: Codable, Hashable {

    public var projectId: UUID?
    public var title: String?
    public var description: String?
    public var dueDate: Date?
    public var assignedUserId: UUID?

    public init(projectId: UUID? = nil, title: String? = nil, description: String? = nil, dueDate: Date? = nil, assignedUserId: UUID? = nil) {
        self.projectId = projectId
        self.title = title
        self.description = description
        self.dueDate = dueDate
        self.assignedUserId = assignedUserId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId
        case title
        case description
        case dueDate
        case assignedUserId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(dueDate, forKey: .dueDate)
        try container.encodeIfPresent(assignedUserId, forKey: .assignedUserId)
    }



}
