//
// SixLinkedCompaniesDtosContactCompanyDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct SixLinkedCompaniesDtosContactCompanyDto: Codable, Hashable {

    public var id: UUID?
    public var name: String?
    public var shortBio: String?
    public var companyLogoId: UUID?
    public var isVerified: Bool?

    public init(id: UUID? = nil, name: String? = nil, shortBio: String? = nil, companyLogoId: UUID? = nil, isVerified: Bool? = nil) {
        self.id = id
        self.name = name
        self.shortBio = shortBio
        self.companyLogoId = companyLogoId
        self.isVerified = isVerified
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case shortBio
        case companyLogoId
        case isVerified
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(shortBio, forKey: .shortBio)
        try container.encodeIfPresent(companyLogoId, forKey: .companyLogoId)
        try container.encodeIfPresent(isVerified, forKey: .isVerified)
    }



}
