//
// VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto: Codable, Hashable {

    public var entities: [String: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto]?
    public var configuration: [String: AnyCodable]?

    public init(entities: [String: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto]? = nil, configuration: [String: AnyCodable]? = nil) {
        self.entities = entities
        self.configuration = configuration
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entities
        case configuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entities, forKey: .entities)
        try container.encodeIfPresent(configuration, forKey: .configuration)
    }



}
