//
// VoloAbpHttpModelingModuleApiDescriptionModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpHttpModelingModuleApiDescriptionModel: Codable, Hashable {

    public var rootPath: String?
    public var remoteServiceName: String?
    public var controllers: [String: VoloAbpHttpModelingControllerApiDescriptionModel]?

    public init(rootPath: String? = nil, remoteServiceName: String? = nil, controllers: [String: VoloAbpHttpModelingControllerApiDescriptionModel]? = nil) {
        self.rootPath = rootPath
        self.remoteServiceName = remoteServiceName
        self.controllers = controllers
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rootPath
        case remoteServiceName
        case controllers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rootPath, forKey: .rootPath)
        try container.encodeIfPresent(remoteServiceName, forKey: .remoteServiceName)
        try container.encodeIfPresent(controllers, forKey: .controllers)
    }



}
