//
// VoloAbpAspNetCoreMvcMultiTenancyFindTenantResultDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpAspNetCoreMvcMultiTenancyFindTenantResultDto: Codable, Hashable {

    public var success: Bool?
    public var tenantId: UUID?
    public var name: String?

    public init(success: Bool? = nil, tenantId: UUID? = nil, name: String? = nil) {
        self.success = success
        self.tenantId = tenantId
        self.name = name
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case tenantId
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(name, forKey: .name)
    }



}
