//
// VoloAbpPermissionManagementUpdatePermissionsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpPermissionManagementUpdatePermissionsDto: Codable, Hashable {

    public var permissions: [VoloAbpPermissionManagementUpdatePermissionDto]?

    public init(permissions: [VoloAbpPermissionManagementUpdatePermissionDto]? = nil) {
        self.permissions = permissions
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(permissions, forKey: .permissions)
    }



}
