//
// VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone: Codable, Hashable {

    public var timeZoneId: String?

    public init(timeZoneId: String? = nil) {
        self.timeZoneId = timeZoneId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeZoneId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timeZoneId, forKey: .timeZoneId)
    }



}
