//
// VoloAbpAccountSendPasswordResetCodeDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpAccountSendPasswordResetCodeDto: Codable, Hashable {

    public var email: String
    public var appName: String
    public var returnUrl: String?
    public var returnUrlHash: String?

    public init(email: String, appName: String, returnUrl: String? = nil, returnUrlHash: String? = nil) {
        self.email = email
        self.appName = appName
        self.returnUrl = returnUrl
        self.returnUrlHash = returnUrlHash
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case appName
        case returnUrl
        case returnUrlHash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(appName, forKey: .appName)
        try container.encodeIfPresent(returnUrl, forKey: .returnUrl)
        try container.encodeIfPresent(returnUrlHash, forKey: .returnUrlHash)
    }



}
