//
// VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone: Codable, Hashable {

    public var iana: VoloAbpAspNetCoreMvcApplicationConfigurationsIanaTimeZone?
    public var windows: VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone?

    public init(iana: VoloAbpAspNetCoreMvcApplicationConfigurationsIanaTimeZone? = nil, windows: VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone? = nil) {
        self.iana = iana
        self.windows = windows
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iana
        case windows
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(iana, forKey: .iana)
        try container.encodeIfPresent(windows, forKey: .windows)
    }



}
