//
// VoloAbpHttpRemoteServiceErrorInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpHttpRemoteServiceErrorInfo: Codable, Hashable {

    public var code: String?
    public var message: String?
    public var details: String?
    public var data: [String: AnyCodable]?
    public var validationErrors: [VoloAbpHttpRemoteServiceValidationErrorInfo]?

    public init(code: String? = nil, message: String? = nil, details: String? = nil, data: [String: AnyCodable]? = nil, validationErrors: [VoloAbpHttpRemoteServiceValidationErrorInfo]? = nil) {
        self.code = code
        self.message = message
        self.details = details
        self.data = data
        self.validationErrors = validationErrors
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case details
        case data
        case validationErrors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(validationErrors, forKey: .validationErrors)
    }



}
