//
// VoloAbpValidationStringValuesIStringValueType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpValidationStringValuesIStringValueType: Codable, Hashable {

    public var name: String?
    public var properties: [String: AnyCodable]?
    public var validator: VoloAbpValidationStringValuesIValueValidator?

    public init(name: String? = nil, properties: [String: AnyCodable]? = nil, validator: VoloAbpValidationStringValuesIValueValidator? = nil) {
        self.name = name
        self.properties = properties
        self.validator = validator
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case properties
        case validator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(properties, forKey: .properties)
        try container.encodeIfPresent(validator, forKey: .validator)
    }



}
