//
// VoloAbpTenantManagementTenantUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpTenantManagementTenantUpdateDto: Codable, Hashable {

    public var extraProperties: [String: AnyCodable]?
    public var name: String

    public init(extraProperties: [String: AnyCodable]? = nil, name: String) {
        self.extraProperties = extraProperties
        self.name = name
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case extraProperties
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(extraProperties, forKey: .extraProperties)
        try container.encode(name, forKey: .name)
    }



}
