//
// VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiDto: Codable, Hashable {

    public var onGet: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiGetDto?
    public var onCreate: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiCreateDto?
    public var onUpdate: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiUpdateDto?

    public init(onGet: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiGetDto? = nil, onCreate: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiCreateDto? = nil, onUpdate: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiUpdateDto? = nil) {
        self.onGet = onGet
        self.onCreate = onCreate
        self.onUpdate = onUpdate
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case onGet
        case onCreate
        case onUpdate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(onGet, forKey: .onGet)
        try container.encodeIfPresent(onCreate, forKey: .onCreate)
        try container.encodeIfPresent(onUpdate, forKey: .onUpdate)
    }



}
