//
// VoloAbpIdentityIdentityRoleCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpIdentityIdentityRoleCreateDto: Codable, Hashable {

    public var extraProperties: [String: AnyCodable]?
    public var name: String
    public var isDefault: Bool?
    public var isPublic: Bool?

    public init(extraProperties: [String: AnyCodable]? = nil, name: String, isDefault: Bool? = nil, isPublic: Bool? = nil) {
        self.extraProperties = extraProperties
        self.name = name
        self.isDefault = isDefault
        self.isPublic = isPublic
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case extraProperties
        case name
        case isDefault
        case isPublic
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(extraProperties, forKey: .extraProperties)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(isPublic, forKey: .isPublic)
    }



}
