//
// VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiGetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyApiGetDto: Codable, Hashable {

    public var isAvailable: Bool?

    public init(isAvailable: Bool? = nil) {
        self.isAvailable = isAvailable
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isAvailable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isAvailable, forKey: .isAvailable)
    }



}
