//
// VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto: Codable, Hashable {

    public var properties: [String: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto]?
    public var configuration: [String: AnyCodable]?

    public init(properties: [String: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto]? = nil, configuration: [String: AnyCodable]? = nil) {
        self.properties = properties
        self.configuration = configuration
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case properties
        case configuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(properties, forKey: .properties)
        try container.encodeIfPresent(configuration, forKey: .configuration)
    }



}
