//
// ChatAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(Combine)
import Combine
#endif

open class ChatAPI {
    /**

     - parameter sixLinkedChatDtosSendMessageInput: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<Void, Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiAppChatSendMessagePost(sixLinkedChatDtosSendMessageInput: SixLinkedChatDtosSendMessageInput? = nil, apiResponseQueue: DispatchQueue = SixProApiAPI.apiResponseQueue) -> AnyPublisher<Void, Error> {
        return Future<Void, Error>.init { promise in
            apiAppChatSendMessagePostWithRequestBuilder(sixLinkedChatDtosSendMessageInput: sixLinkedChatDtosSendMessageInput).execute(apiResponseQueue) { result -> Void in
                switch result {
                case .success:
                    promise(.success(()))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     - POST /api/app/chat/send-message
     - parameter sixLinkedChatDtosSendMessageInput: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiAppChatSendMessagePostWithRequestBuilder(sixLinkedChatDtosSendMessageInput: SixLinkedChatDtosSendMessageInput? = nil) -> RequestBuilder<Void> {
        let path = "/api/app/chat/send-message"
        let URLString = SixProApiAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sixLinkedChatDtosSendMessageInput)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SixProApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter sixLinkedChatDtosSendMessageInput: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<Void, Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendMessagePost(sixLinkedChatDtosSendMessageInput: SixLinkedChatDtosSendMessageInput? = nil, apiResponseQueue: DispatchQueue = SixProApiAPI.apiResponseQueue) -> AnyPublisher<Void, Error> {
        return Future<Void, Error>.init { promise in
            sendMessagePostWithRequestBuilder(sixLinkedChatDtosSendMessageInput: sixLinkedChatDtosSendMessageInput).execute(apiResponseQueue) { result -> Void in
                switch result {
                case .success:
                    promise(.success(()))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     - POST /send-message
     - parameter sixLinkedChatDtosSendMessageInput: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func sendMessagePostWithRequestBuilder(sixLinkedChatDtosSendMessageInput: SixLinkedChatDtosSendMessageInput? = nil) -> RequestBuilder<Void> {
        let path = "/send-message"
        let URLString = SixProApiAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sixLinkedChatDtosSendMessageInput)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SixProApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
