//
// FeaturesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(Combine)
import Combine
#endif

open class FeaturesAPI {
    /**

     - parameter providerName: (query)  (optional)
     - parameter providerKey: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<VoloAbpFeatureManagementGetFeatureListResultDto, Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiFeatureManagementFeaturesGet(providerName: String? = nil, providerKey: String? = nil, apiResponseQueue: DispatchQueue = SixProApiAPI.apiResponseQueue) -> AnyPublisher<VoloAbpFeatureManagementGetFeatureListResultDto, Error> {
        return Future<VoloAbpFeatureManagementGetFeatureListResultDto, Error>.init { promise in
            apiFeatureManagementFeaturesGetWithRequestBuilder(providerName: providerName, providerKey: providerKey).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     - GET /api/feature-management/features
     - parameter providerName: (query)  (optional)
     - parameter providerKey: (query)  (optional)
     - returns: RequestBuilder<VoloAbpFeatureManagementGetFeatureListResultDto> 
     */
    open class func apiFeatureManagementFeaturesGetWithRequestBuilder(providerName: String? = nil, providerKey: String? = nil) -> RequestBuilder<VoloAbpFeatureManagementGetFeatureListResultDto> {
        let path = "/api/feature-management/features"
        let URLString = SixProApiAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "providerName": providerName?.encodeToJSON(),
            "providerKey": providerKey?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<VoloAbpFeatureManagementGetFeatureListResultDto>.Type = SixProApiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter providerName: (query)  (optional)
     - parameter providerKey: (query)  (optional)
     - parameter voloAbpFeatureManagementUpdateFeaturesDto: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<Void, Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiFeatureManagementFeaturesPut(providerName: String? = nil, providerKey: String? = nil, voloAbpFeatureManagementUpdateFeaturesDto: VoloAbpFeatureManagementUpdateFeaturesDto? = nil, apiResponseQueue: DispatchQueue = SixProApiAPI.apiResponseQueue) -> AnyPublisher<Void, Error> {
        return Future<Void, Error>.init { promise in
            apiFeatureManagementFeaturesPutWithRequestBuilder(providerName: providerName, providerKey: providerKey, voloAbpFeatureManagementUpdateFeaturesDto: voloAbpFeatureManagementUpdateFeaturesDto).execute(apiResponseQueue) { result -> Void in
                switch result {
                case .success:
                    promise(.success(()))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     - PUT /api/feature-management/features
     - parameter providerName: (query)  (optional)
     - parameter providerKey: (query)  (optional)
     - parameter voloAbpFeatureManagementUpdateFeaturesDto: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiFeatureManagementFeaturesPutWithRequestBuilder(providerName: String? = nil, providerKey: String? = nil, voloAbpFeatureManagementUpdateFeaturesDto: VoloAbpFeatureManagementUpdateFeaturesDto? = nil) -> RequestBuilder<Void> {
        let path = "/api/feature-management/features"
        let URLString = SixProApiAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: voloAbpFeatureManagementUpdateFeaturesDto)

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "providerName": providerName?.encodeToJSON(),
            "providerKey": providerKey?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SixProApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
