//
// InvitationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(Combine)
import Combine
#endif

open class InvitationAPI {
    /**

     - parameter isUsed: (query)  (optional)
     - parameter invitationType: (query)  (optional)
     - parameter filter: (query)  (optional)
     - parameter sorting: (query)  (optional)
     - parameter skipCount: (query)  (optional)
     - parameter maxResultCount: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<VoloAbpApplicationDtosPagedResultDto1SixLinkedInvitationsDtosSimpleInvitationDtoSixLinkedApplicationContractsVersion1000CultureneutralPublicKeyTokennull, Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiAppInvitationGet(isUsed: Bool? = nil, invitationType: SixLinkedInvitationsInvitationType? = nil, filter: String? = nil, sorting: String? = nil, skipCount: Int? = nil, maxResultCount: Int? = nil, apiResponseQueue: DispatchQueue = SixProApiAPI.apiResponseQueue) -> AnyPublisher<VoloAbpApplicationDtosPagedResultDto1SixLinkedInvitationsDtosSimpleInvitationDtoSixLinkedApplicationContractsVersion1000CultureneutralPublicKeyTokennull, Error> {
        return Future<VoloAbpApplicationDtosPagedResultDto1SixLinkedInvitationsDtosSimpleInvitationDtoSixLinkedApplicationContractsVersion1000CultureneutralPublicKeyTokennull, Error>.init { promise in
            apiAppInvitationGetWithRequestBuilder(isUsed: isUsed, invitationType: invitationType, filter: filter, sorting: sorting, skipCount: skipCount, maxResultCount: maxResultCount).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     - GET /api/app/invitation
     - parameter isUsed: (query)  (optional)
     - parameter invitationType: (query)  (optional)
     - parameter filter: (query)  (optional)
     - parameter sorting: (query)  (optional)
     - parameter skipCount: (query)  (optional)
     - parameter maxResultCount: (query)  (optional)
     - returns: RequestBuilder<VoloAbpApplicationDtosPagedResultDto1SixLinkedInvitationsDtosSimpleInvitationDtoSixLinkedApplicationContractsVersion1000CultureneutralPublicKeyTokennull> 
     */
    open class func apiAppInvitationGetWithRequestBuilder(isUsed: Bool? = nil, invitationType: SixLinkedInvitationsInvitationType? = nil, filter: String? = nil, sorting: String? = nil, skipCount: Int? = nil, maxResultCount: Int? = nil) -> RequestBuilder<VoloAbpApplicationDtosPagedResultDto1SixLinkedInvitationsDtosSimpleInvitationDtoSixLinkedApplicationContractsVersion1000CultureneutralPublicKeyTokennull> {
        let path = "/api/app/invitation"
        let URLString = SixProApiAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "IsUsed": isUsed?.encodeToJSON(),
            "InvitationType": invitationType?.encodeToJSON(),
            "Filter": filter?.encodeToJSON(),
            "Sorting": sorting?.encodeToJSON(),
            "SkipCount": skipCount?.encodeToJSON(),
            "MaxResultCount": maxResultCount?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<VoloAbpApplicationDtosPagedResultDto1SixLinkedInvitationsDtosSimpleInvitationDtoSixLinkedApplicationContractsVersion1000CultureneutralPublicKeyTokennull>.Type = SixProApiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter id: (query)  (optional)
     - parameter isUsed: (query)  (optional)
     - parameter invitationType: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<SixLinkedInvitationsDtosSimpleInvitationDto, Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiAppInvitationInvitationByIdGet(id: UUID? = nil, isUsed: Bool? = nil, invitationType: SixLinkedInvitationsInvitationType? = nil, apiResponseQueue: DispatchQueue = SixProApiAPI.apiResponseQueue) -> AnyPublisher<SixLinkedInvitationsDtosSimpleInvitationDto, Error> {
        return Future<SixLinkedInvitationsDtosSimpleInvitationDto, Error>.init { promise in
            apiAppInvitationInvitationByIdGetWithRequestBuilder(id: id, isUsed: isUsed, invitationType: invitationType).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    promise(.success(response.body!))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     - GET /api/app/invitation/invitation-by-id
     - parameter id: (query)  (optional)
     - parameter isUsed: (query)  (optional)
     - parameter invitationType: (query)  (optional)
     - returns: RequestBuilder<SixLinkedInvitationsDtosSimpleInvitationDto> 
     */
    open class func apiAppInvitationInvitationByIdGetWithRequestBuilder(id: UUID? = nil, isUsed: Bool? = nil, invitationType: SixLinkedInvitationsInvitationType? = nil) -> RequestBuilder<SixLinkedInvitationsDtosSimpleInvitationDto> {
        let path = "/api/app/invitation/invitation-by-id"
        let URLString = SixProApiAPI.basePath + path
        let parameters: [String: Any]? = nil

        var urlComponents = URLComponents(string: URLString)
        urlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Id": id?.encodeToJSON(),
            "IsUsed": isUsed?.encodeToJSON(),
            "InvitationType": invitationType?.encodeToJSON(),
        ])

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<SixLinkedInvitationsDtosSimpleInvitationDto>.Type = SixProApiAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**

     - parameter sixLinkedInvitationsDtosCreateNewInvitationDto: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: AnyPublisher<Void, Error>
     */
    #if canImport(Combine)
    @available(OSX 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiAppInvitationInvitationPost(sixLinkedInvitationsDtosCreateNewInvitationDto: SixLinkedInvitationsDtosCreateNewInvitationDto? = nil, apiResponseQueue: DispatchQueue = SixProApiAPI.apiResponseQueue) -> AnyPublisher<Void, Error> {
        return Future<Void, Error>.init { promise in
            apiAppInvitationInvitationPostWithRequestBuilder(sixLinkedInvitationsDtosCreateNewInvitationDto: sixLinkedInvitationsDtosCreateNewInvitationDto).execute(apiResponseQueue) { result -> Void in
                switch result {
                case .success:
                    promise(.success(()))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }.eraseToAnyPublisher()
    }
    #endif

    /**
     - POST /api/app/invitation/invitation
     - parameter sixLinkedInvitationsDtosCreateNewInvitationDto: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiAppInvitationInvitationPostWithRequestBuilder(sixLinkedInvitationsDtosCreateNewInvitationDto: SixLinkedInvitationsDtosCreateNewInvitationDto? = nil) -> RequestBuilder<Void> {
        let path = "/api/app/invitation/invitation"
        let URLString = SixProApiAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sixLinkedInvitationsDtosCreateNewInvitationDto)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SixProApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
